### PR TITLE
Update NLoptNet to .NetStandard2.0

### PR DESCRIPTION
**Pull request by Marjolein-1234**
This pull request contains the necessary changes for NLoptNet to work on .Net Standard 2.0.
@BrannonKing Can you review this PR and create an official updated version of NLoptNet?

### CODE REVIEW

**Comment by BrannonKing** [comment]
I'm going to make further changes after the merge to support the newer native asset layout.

**Comment by BrannonKing** [comment]
When I change it to use the Pack & PackagePath properties, it no longer works in the old packages.config approach. Do you think that is acceptable?

**Comment by Marjolein-1234** [comment]
As long as the Nuget package works, it is acceptable I think. The newer csproj format is not compatible with the old packages.config approach.

**Comment by BrannonKing** [comment]
I've pushed the update to nuget.org

**Pull request merged**
